name = "FixedPointAcceleration"
uuid = "817d07cb-a79a-5c30-9a31-890123675176"
authors = ["Stuart Baumann <stuart@stuartbaumann.com>"]
version = "1.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
GLM = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
Aqua = "0.8"
Dates = "<0.0.1, 1"
GLM = "^1"
LinearAlgebra = "<0.0.1, 1"
Test = "<0.0.1, 1"
julia = "^1.4"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
